### ISSUE TITLE
ACATsetup.exe not found in downloaded acat-0.9.1.zip

### ISSUE THREAD

**Issue by Tapan-Aggarwal** [intel/acat#12]
Your ACAT page in this repository is saying you would be releasing the new version of ACAT soon is that the reason the downloaded acat-0.9.1.zip is not having ACATsetup.exe file. If that is so how soon would intel put the ACATsetup.exe in the GITHUB repository for the us to download.
Thanks & regards,
Tapan Aggarwal
Delhi India

**Comment by tarsiscr** [comment]
Hello, I need to try it.
Could u help me, sending me an email when the setup is avaliable?
Thks
Társis

**Comment by nanomo** [comment]
they say it will be available later this week, stay in touch :)

**Comment by niyazialpay** [comment]
I can't find too

**Comment by Micheli123** [comment]
Im having the same problem i can not find the ACATsetup.exe file.

Please could you help us?
