### ISSUE TITLE
No scanner - settings modification

### ISSUE THREAD

**Issue by samalkah** [intel/acat#25]
Hi,
I encounter a very bad issue after having modified the "Scan Settings" in the "Timings" section.

First of all I noticed the scanner don't select any field of the "Timings" section. So I tryed to change one setting like "WordList Pause" (but the issue come with any change in these fields) with the mouse and just after that the yellow scanner disappeared and never come back (even when pressing the F12 or F5 key). 
There is a Default button but the Scanner doesn't come back.
Even worse, it doesn't change anything if you restart ACAT and your computer. I had do delete manually "Users" directory to make the Scanner work again.

**Comment by nanomo** [comment]
Seems to be an issue with the xml read/write functions, when you change it it will break the xml structure, i had the same issue but i didn't fixed at the moment, i think it will be very usefull if all start to make pull requests :)
