### ISSUE TITLE
Running ACAT as a user

### ISSUE THREAD

**Issue by LaurentBerger** [intel/acat#28]
Hi,

Is it possible to run ACAT as a user?
I have installed ACAT as administrator. I can run acat but I cannot run as a simple user.

Thanks for your answer.

**Comment by nanomo** [comment]
did you receive any message?

**Comment by LaurentBerger** [comment]
No I didn't

**Comment by saiprasadb01** [comment]
ACAT doesn't really need admin rights to run.  To which folder did you install ACAT?  Did you install it to the default location c:\intel\acat?   And what happens when you run as a user?

**Comment by LaurentBerger** [comment]
I have done a standard install but when I run acat it cannot found presage database (in an user account). Using admin account on same machine acat run. (Windows 10 pro)

**Comment by saiprasadb01** [comment]
Maybe you can go into Windows User Manager and add the user to the Administrator group. Go to Control Panel, select "User Accounts"
