### ISSUE TITLE
Cannot build installer

### ISSUE THREAD

**Issue by bergmeister** [intel/acat#32]
Although I installed InstallShield, I cannot build the installer of the ACATSetup.sln project
There clearly is hard-coded dependency to the authors drive items (more than 200!) such as
C:\Users\sprasad1\Documents\Projects\EPL Glen Ellyn\Hawking\ACAT-1\OpenSource\Src\Applications\Setup\Extensions\Default\FunctionalAgents\AbbreviationsAgent\AbbreviationEditDeleteConfirm.xml
Any workarounds? Also, when I setup my local development environment, it looked like as if there is a dependency to an actual installation even if the presage database engine gets copied to its correct location?

**Comment by CrystalSpore** [comment]
I don't know of a work around. I just want to tag on that when building the project, it instantly crashes when trying to load up the camera. This makes it impossible to try to run the project from source.
