### ISSUE TITLE
How to change the voice from male to female?

### ISSUE THREAD

**Issue by afyoung3083** [intel/acat#34]
My father has ALS and is new to the software. One issue that bothers him is the default voice is female, but he would like the default voice to be male. How can we change the default voice?

**Comment by saiprasadb01** [comment]
The next release which will be up next week will enable you to select the preferred voice for text-to-speech

**Comment by saiprasadb01** [comment]
We have released v0.99.1 [here](https://github.com/01org/acat/releases).  A number of new features have been added including selection of the preferred voice for text-to-speech
