### ISSUE TITLE
Cannot select voice in V1.0

### ISSUE THREAD

**Issue by molerat619** [intel/acat#43]
I am running ACAT App on Windows 10 in Version 1.0.0 and I cannot change the voice for TTS.

In my windows settings, I have following voices available (german):

![image](https://cloud.githubusercontent.com/assets/3458576/21395512/08d449c8-c79d-11e6-9954-5cdf6bc8907b.png)

Stefan is selected and in my ACAT configuration I picked **male**, but I can't select a voice in the top:

![image](https://cloud.githubusercontent.com/assets/3458576/21395502/fbf0f36e-c79c-11e6-9c5e-d9236db4bb66.png)

I need a male voice and ACAT TTS reads with a female voice, ignoring my settings.

What can I do here? Thanks.

**Comment by zelmon64** [comment]
@molerat619 Have you had any luck with this? I found it can be changed by selecting the computer's default voice in the Control Panel. Search for  "text to speech settings" (or the german equivalent) to find it:

![image](https://cloud.githubusercontent.com/assets/15001389/25312297/e67ddc46-280d-11e7-81c3-de0091cdfe31.png)

**Comment by sofiamf** [comment]
Did you find a solution for this? @molerat619 @zelmon64 
I was able to add the portuguese language pack to the options
![image](https://user-images.githubusercontent.com/24230120/30007147-255fd2e2-9100-11e7-9aa1-638bace5a01d.png)
However, ACAT is ignoring this settings and after use I go check this windows and it has been changed.

Thanks in advance.

**Comment by molerat619** [comment]
@sofiamf @zelmon64 Sorry, but no, I have not worked on this for a while and the latest state was that it did not work for me. Maybe now with the latest version of ACAT it works. I will let you know once I try it again.

**Comment by sofiamf** [comment]
@molerat619 Okay, many thanks! Let me know then please :)

**Comment by RafaelScience** [comment]
I could not find the solution to solve this problem, could anyone?
