### ISSUE TITLE
Mouse Click/IR Finger as an F12 Trigger

### ISSUE THREAD

**Issue by RalfCT** [intel/acat#47]
I downloaded ACAT a few days ago, it's amazing!  Using F12 as a trigger is not practical in my prospective application, neither is the webcam trigger (the MS patient has limited facial/hand movement).

1.  Is it possible to configure a mouse left and right-clicks to be an F12 trigger?  
2.  Is it possible to also scroll backwards, rather than scrolling through all the words to get back to the one that was missed?  Left-click scrolls forwards, right-click scrolls backwards?
3.  How would I configure an IR sensor connected to a finger to simulate the F12 trigger?  Where could one purchase such a sensor?

**Comment by zelmon64** [comment]
> Is it possible to configure a mouse left and right-clicks to be an F12 trigger?

@RalfCT Have you tried using an AutoHotkey script as described [here ](https://github.com/01org/acat/issues/26#issuecomment-198670003)in issue #26? It worked for me.

I don't know about your other questions.
