### ISSUE TITLE
Pressing F12 selects the subsequent word, not the highlighted word

### ISSUE THREAD

**Issue by RalfCT** [intel/acat#48]
When clicking the highlighted word the software seems to delay and select the next word in the word list.  This can be frustrating when one constantly has to delete and try again.  Scrolling speeds between screens are on default.  Is this a bug or can it be adjusted?

**Comment by zelmon64** [comment]
@RalfCT I found the error is in some of the [AlphabetScanner .xml files](https://github.com/01org/acat/tree/master/src/ACATResources/en). For example [here in the AlphabetScannerAlternate.xml file](https://github.com/01org/acat/blob/master/src/ACATResources/en/AlphabetScannerAlternate.xml#L228-#L235).

The correct form is:

`<Widget name="PWLItem1" onSelect="actuate(PWLItem1);transition(TopLevelRotation)"/>`

Changing the .xml file for the layout you use will fix it.
