### ISSUE TITLE
Computer vision based algorithm for an ACAT actuator 

### ISSUE THREAD

**Issue by DavidHuji** [intel/acat#69]
Hi :) 

I'm working on a generic algorithm for identifying small face movements so patients could use it as an ACAT actuator. It already works fine for one ALS patient who tried it. Is there a chance we can pull it to this project so others (patients as well as developers) could benefit it?

**Comment by marioj2816** [comment]
hello I am interested in your project you can contact me and my email please marioj2816@hotmail.com
