### ISSUE TITLE
Support for iOS devices

### ISSUE THREAD

**Issue by sambudda** [intel/acat#9]
I understand that this is intel / microsoft project and they would like to advertise it for windows phones but most people are on either android or iOS phones.

Is there any plans to support this great project for iOS platform? If no then how can I convert it into iOS compatible code to use it in my app?

**Comment by artdrozdov** [comment]
Waht about Xamarin?

**Comment by tarekselem** [comment]
Xamarin.Forms will be perfect native with more work around and technical challenges.

But in case hyper app. What about ionic??
